/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.appcrudoracle.cl.presentacion;

import com.appcrudoracle.cl.entidades.Cliente;
import com.appcrudoracle.cl.entidades.Comuna;
import com.appcrudoracle.cl.negocio.negCliente;
import com.appcrudoracle.cl.negocio.negComuna;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CETECOM
 */
public class FrmMantenedorClientes extends javax.swing.JFrame {
    private HashMap<String,Integer> mapComunas = new HashMap<String,Integer>();
    private negCliente nCli = new negCliente();
    /**
     * Creates new form FrmMantenedorClientes
     */
    public FrmMantenedorClientes() {
        initComponents();
        llenarComunas();
        llenarTabla();
        limpiarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgEstadoCivil = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        pnlDatos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        cboComuna = new javax.swing.JComboBox<>();
        rdbSoltero = new javax.swing.JRadioButton();
        rdbCasado = new javax.swing.JRadioButton();
        rdbUnionCivil = new javax.swing.JRadioButton();
        chkJava = new javax.swing.JCheckBox();
        chkCSharp = new javax.swing.JCheckBox();
        chkJS = new javax.swing.JCheckBox();
        btnGrabar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MANTENEDOR DE CLIENTES");

        jLabel2.setText("Rut:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Comuna:");

        jLabel5.setText("Estado Civil:");

        jLabel6.setText("Lenguaje Preferencia:");

        bgEstadoCivil.add(rdbSoltero);
        rdbSoltero.setSelected(true);
        rdbSoltero.setText("Soltero");

        bgEstadoCivil.add(rdbCasado);
        rdbCasado.setText("Casado");

        bgEstadoCivil.add(rdbUnionCivil);
        rdbUnionCivil.setText("Union Civil");

        chkJava.setText("Java");

        chkCSharp.setText("C#");

        chkJS.setText("JS");

        btnGrabar.setText("Grabar");
        btnGrabar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGrabarMouseClicked(evt);
            }
        });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rut", "Nombre", "Comuna", "Estado Civil", "Lenguajes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblClientes);

        btnModificar.setText("Modificar");
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3)
                                .addComponent(jLabel6))
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(chkJava, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnLimpiar)
                                    .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtRut, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                            .addComponent(txtNombre))
                                        .addGroup(pnlDatosLayout.createSequentialGroup()
                                            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cboComuna, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(rdbSoltero, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addGap(41, 41, 41)
                                            .addComponent(rdbCasado)
                                            .addGap(26, 26, 26)
                                            .addComponent(rdbUnionCivil))
                                        .addGroup(pnlDatosLayout.createSequentialGroup()
                                            .addGap(64, 64, 64)
                                            .addComponent(chkCSharp, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(chkJS, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnGrabar)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rdbSoltero)
                    .addComponent(rdbCasado)
                    .addComponent(rdbUnionCivil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(chkJava)
                    .addComponent(chkCSharp)
                    .addComponent(chkJS))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrabar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel1)
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean validaObligatorios()
    {
        boolean valido = true;
        String validaText = "";
        if(txtRut.getText().trim().isEmpty())
        {
            valido = false;
            validaText += "Rut es obligaotrio \n";
        }
        if(txtNombre.getText().trim().isEmpty())
        {
            valido = false;
            validaText += "Nombre es obligatorio \n";
        }
        if(mapComunas.get(cboComuna.getSelectedItem().toString()) == 0)
        {
            valido = false;
            validaText += "Debe seleccionar una comuna\n";
        }
        if(!chkJava.isSelected())
        {
            valido = false;
            validaText += "Debe seleccionar al menos el lenguaje JAVA";   
        }
        if(!valido)
        {
            JOptionPane.showMessageDialog(null, validaText);
        }
        return valido;
    }
    private void btnGrabarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGrabarMouseClicked
        // TODO add your handling code here:
        if(validaObligatorios())
        {
            String rut = txtRut.getText();
            String nombre = txtNombre.getText();
            String comuna = cboComuna.getSelectedItem().toString();
            int id_comuna = mapComunas.get(cboComuna.getSelectedItem().toString());
            String estado = "";
            String lenguajes = "";
            Cliente cli = new Cliente();
            if(rdbSoltero.isSelected())
            {
                estado = "Soltero";
            }
            else
            {
                if(rdbCasado.isSelected())
                {
                    estado = "Casado";
                }
                else
                {
                    estado = "Union Civil";
                }
            }
            if(chkJava.isSelected())
            {
                lenguajes += "JAVA,";
            }
            if(chkCSharp.isSelected())
            {
                lenguajes += "C#,";
            }
            if(chkJS.isSelected())
            {
                lenguajes += "JA,";
            }
            cli.setRut(rut);
            cli.setNombre(nombre);
            cli.setComuna(comuna);
            cli.setId_comuna(id_comuna);
            cli.setEstadoCivil(estado);
            cli.setLenguajes(lenguajes);
            if(nCli.agregar(cli))
            {
                JOptionPane.showMessageDialog(null, "Dator Grabados!!");
                limpiarTodo();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "UPS!!! no se grabaron los datos!!");
                limpiarTodo();

            }
        }
        else
        {
            limpiarTodo();
        } 
    }//GEN-LAST:event_btnGrabarMouseClicked

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        // TODO add your handling code here:
        int fila = tblClientes.getSelectedRow();
        if(fila != -1)
        {
            limpiarFormulario();
            String rut = tblClientes.getValueAt(fila, 0).toString();
            String nombre = tblClientes.getValueAt(fila, 1).toString();
            String comuna = tblClientes.getValueAt(fila, 2).toString();
            String estado = tblClientes.getValueAt(fila, 3).toString();
            String lenguajes = tblClientes.getValueAt(fila, 4).toString();
            String[] listaLenguajes = lenguajes.split(",");
            txtRut.setText(rut);
            txtNombre.setText(nombre);
            cboComuna.setSelectedItem(comuna);
            if(estado.equalsIgnoreCase("Casado"))
            {
                rdbCasado.setSelected(true);
            }
            else
            {
                if(estado.equalsIgnoreCase("Soltero"))
                {
                    rdbSoltero.setSelected(true);
                }
                else
                {
                    rdbUnionCivil.setSelected(true);
                }
            }
            for(String leng : listaLenguajes)
            {
                if(!leng.isEmpty())
                {
                    if(leng.equalsIgnoreCase("JAVA"))
                    {
                        chkJava.setSelected(true);
                    }
                    if(leng.equalsIgnoreCase("C#"))
                    {
                        chkCSharp.setSelected(true);
                    }
                    if(leng.equalsIgnoreCase("JS"))
                    {
                        chkJS.setSelected(true);
                    }
                
                
                }
            
            }
            txtRut.setEnabled(false);
            btnGrabar.setEnabled(false);
            btnModificar.setEnabled(true);
            btnEliminar.setEnabled(true);
        }
    }//GEN-LAST:event_tblClientesMouseClicked

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        // TODO add your handling code here:
        limpiarTodo();
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        // TODO add your handling code here:
        if(validaObligatorios())
        {
            String rut = txtRut.getText();
            String nombre = txtNombre.getText();
            String comuna = cboComuna.getSelectedItem().toString();
            int id_comuna = mapComunas.get(cboComuna.getSelectedItem().toString());
            String estado = "";
            String lenguajes = "";
            Cliente cli = new Cliente();
            if(rdbSoltero.isSelected())
            {
                estado = "Soltero";
            }
            else
            {
                if(rdbCasado.isSelected())
                {
                    estado = "Casado";
                }
                else
                {
                    estado = "Union Civil";
                }
            }
            if(chkJava.isSelected())
            {
                lenguajes += "JAVA,";
            }
            if(chkCSharp.isSelected())
            {
                lenguajes += "C#,";
            }
            if(chkJS.isSelected())
            {
                lenguajes += "JA,";
            }
            cli.setRut(rut);
            cli.setNombre(nombre);
            cli.setComuna(comuna);
            cli.setId_comuna(id_comuna);
            cli.setEstadoCivil(estado);
            cli.setLenguajes(lenguajes);
            if(nCli.modificar(cli))
            {
                JOptionPane.showMessageDialog(null, "Dator Modificados!!");
                limpiarTodo();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "UPS!!! no se modifcaron los datos!!");
                limpiarTodo();

            }
        }
        else
        {
            limpiarTodo();
        }
    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
        String rut = txtRut.getText();
        
        Cliente cli = new Cliente();
        
        cli.setRut(rut);
        
        if(nCli.eliminar(cli))
        {
            JOptionPane.showMessageDialog(null, "Dator Eliminados!!");
            limpiarTodo();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "UPS!!! no se eliminar los datos!!");
            limpiarTodo();
        
        }
    }//GEN-LAST:event_btnEliminarMouseClicked
    private void limpiarTodo()
    {
        DefaultTableModel dm = (DefaultTableModel) tblClientes.getModel();
        dm.getDataVector().removeAllElements();
        llenarTabla();
        limpiarFormulario();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMantenedorClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMantenedorClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMantenedorClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMantenedorClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMantenedorClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgEstadoCivil;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cboComuna;
    private javax.swing.JCheckBox chkCSharp;
    private javax.swing.JCheckBox chkJS;
    private javax.swing.JCheckBox chkJava;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JRadioButton rdbCasado;
    private javax.swing.JRadioButton rdbSoltero;
    private javax.swing.JRadioButton rdbUnionCivil;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables

    private void llenarComunas() {
        negComuna nComuna = new negComuna();
        ArrayList<Comuna> lComuna = new ArrayList<Comuna>();
        lComuna = nComuna.listarTodo();
        
        
        cboComuna.addItem("Seleccione");
        mapComunas.put("Seleccione", 0);
        for(Comuna com : lComuna)
        {
            cboComuna.addItem(com.getNombre());
            mapComunas.put(com.getNombre(), com.getId_comuna());
        }
        
        
        
    }

    private void llenarTabla() {
        //Objetos para recibir los datos
        ArrayList<Cliente> lCli = new ArrayList<Cliente>();
        lCli = nCli.listarTodo();
        //Objetos para llenar la tabla
        DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();
        Object[] fila = new Object[5];
        for(Cliente cli : lCli)
        {
            fila[0] = cli.getRut();
            fila[1] = cli.getNombre();
            fila[2] = cli.getComuna();
            fila[3] = cli.getEstadoCivil();
            fila[4] = cli.getLenguajes();
            modelo.addRow(fila);
        }
        tblClientes.setModel(modelo);
    }

    private void limpiarFormulario() {
        txtRut.setText("");
        txtNombre.setText("");
        cboComuna.setSelectedIndex(0);
        chkJava.setSelected(false);
        chkCSharp.setSelected(false);
        chkJS.setSelected(false);
        rdbSoltero.setSelected(true);
        txtRut.setEnabled(true);
        txtRut.requestFocus();
        btnGrabar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }
}
